### ISSUE TITLE
Tell me a funny story of a time your teacher or professor did not understand how to use technology.

### ISSUE THREAD

**Issue by kbodwin** [Cal-Poly-Advanced-R/Week_0#2]
Leave your answer below.

**Comment by tbaskaran** [comment]
One day the professor was teaching with the aid of an **audio**  and he wanted to change the volume of the audio file. He searched the *volume control icon*, but he could not find it as it was made hidden. The professor  got confused.

**Comment by josh-rowe** [comment]
One of the professors I do research with could never figure out how to allow participants to share their screens in zoom calls, so they would re-start the meeting or make students the meeting host so they could screen share, instead of checking the box which would allow participants to share screens.
